"""add price_snapshot to OrderItem

Revision ID: c8aba93765c5
Revises: 2fe30a3f194b
Create Date: 2026-07-17 13:41:58.376377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8aba93765c5'
down_revision = '2fe30a3f194b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_snapshot', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_column('price_snapshot')

    # ### end Alembic commands ###
